[package]
name = "atlas_users"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
chrono = { version = "0.4.45", features = ["serde"] }
thiserror = "2.0.18"
uuid = { version = "1.23.1", features = ["v7", "serde"] }

[dev-dependencies]
fake = { version = "5.1.0", features = ["email_address"] }
